services:
  - type: web
    name: project-management-api
    env: node
    buildCommand: npm ci
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: project-management-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
    healthCheckPath: /health

databases:
  - name: project-management-db
    databaseName: project_management
    plan: free
    ipAllowList: [] 