services:
  - type: web
    name: project-management-api
    env: node
    nodeVersion: 18.17.1
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: project-management-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true 