services:
  - type: web
    name: project-management-api
    env: node
    buildCommand: npm ci
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
    healthCheckPath: /health

databases:
  - name: project-management-db
    databaseName: project_management_1u0f
    plan: free
    ipAllowList: [] 