services:
  - type: web
    name: project-management-api
    env: node
    buildCommand: npm ci && npx sequelize-cli db:migrate
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: DB_USERNAME
        value: project_management_1u0f_user
      - key: DB_PASSWORD
        value: en1hTRzQBhOUmY1fJ2OfO0DmvvsMJxVL
      - key: DB_NAME
        value: project_management_1u0f
      - key: DB_HOST
        value: dpg-cu2fkr52ng1s7381l84g-a.singapore-postgres.render.com
      - key: PORT
        value: 10000
    healthCheckPath: /health

databases:
  - name: project-management-db
    databaseName: project_management_1u0f
    plan: free
    ipAllowList: [] 